routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\FrontController@index')->name('frontend.index');

Route::get('/dashboard', 'Backend\DashboardController@index')->name('backend.dashboard')->middleware('auth');

Route::resource('/backend/sejarah', 'Backend\SejarahController')->middleware('isWebAdmin');

Route::resource('/backend/tugas-fungsi', 'Backend\TugasFungsiController')->middleware('isWebAdmin');

Route::resource('/backend/struktur-organisasi', 'Backend\StrukturOrganisasiController')->middleware('isWebAdmin');

Route::resource('/backend/visi-misi', 'Backend\VisiMisiController')->middleware('isWebAdmin');

Route::resource('/backend/hubungi-kami', 'Backend\HubungiKamiController')->middleware('isWebAdmin');

Route::resource('/backend/ventura', 'Backend\VenturaController');

Route::resource('/backend/laporan-ventura', 'Backend\LaporanVenturaController')->middleware('isKepalaVentura');

Route::get('/backend/all/laporan-ventura', 'Backend\LaporanVenturaController@getall')->name('laporan-ventura.all');

Route::get('/backend/laporan-ventura/detail/{id}', 'Backend\LaporanVenturaController@detail')->name('laporan-ventura.detail');

Route::resource('/backend/kategori-berita', 'Backend\KategoriBeritaController')->middleware('isWebAdmin');

Route::resource('/backend/berita', 'Backend\BeritaController')->middleware('isWebAdmin');

Route::resource('/backend/galeri-foto', 'Backend\GaleriFotoController')->middleware('isWebAdmin');

Route::resource('/backend/galeri-video', 'Backend\GaleriVideoController')->middleware('isWebAdmin');

Route::resource('/backend/slider', 'Backend\SliderController')->middleware('isWebAdmin');

Route::resource('/backend/jenis-instansi', 'Backend\JenisInstansiController')->middleware('isAdminKerjasama');

Route::resource('/backend/sifat-kerjasama', 'Backend\SifatKerjasamaController')->middleware('isAdminKerjasama');

Route::resource('/backend/instansi', 'Backend\InstansiController')->middleware('isAdminKerjasama');

Route::resource('/backend/kerjasama', 'Backend\KerjasamaController');

Route::get('detail-kerjasama/{id}', 'Backend\KerjasamaController@detail');

Route::get('/backend/kerjasama/download-dokumen/{filename}', 'Backend\KerjasamaController@download')->name('kerjasama.download');

Route::get('hapus-dokumen-kerjasama/{id}', 'Backend\DokumenKerjasamaController@delete')->name('dokumen-kerjasama.destroy');

Route::get('hapus-dokumen-ventura/{id}', 'Backend\DokumenVenturaController@delete')->name('dokumen-ventura.destroy');

Route::resource('/backend/regulasi', 'Backend\RegulasiController')->middleware('isWebAdmin');

Route::resource('/backend/pengguna', 'Backend\PenggunaController')->middleware('isWebAdmin');

Route::get('/backend/rekapitulasi-kerjasama', 'Backend\RekapitulasiKerjasamaController@chart')->name('rekap-kerjasama.index');

Route::resource('/backend/client', 'Backend\ClientController')->middleware('isKepalaVentura');

Route::get('/backend/admin/client', 'Backend\ClientController@getall')->name('client.all');

Route::resource('/backend/laporan-keuangan', 'Backend\LaporanKeuanganController');

Route::resource('/backend/status-usulan', 'Backend\StatusUsulanController')->middleware('isAdminKerjasama');

Route::post('kontribusi-ui/store/{id}', 'Backend\LaporanKeuanganController@kontribusi')->name('kontribusi-ui.store');

Route::get('/profile/sejarah', 'Frontend\ProfileController@sejarah')->name('front.sejarah');

Route::get('/profile/tugas-fungsi', 'Frontend\ProfileController@tugasfungsi')->name('front.tugas');

Route::get('/profile/struktur-organisasi', 'Frontend\ProfileController@strukturorg')->name('front.struktur');

Route::get('/profile/visi-misi', 'Frontend\ProfileController@visimisi')->name('front.visi');

Route::get('/profile/hubungi-kami', 'Frontend\ProfileController@hubungi')->name('front.hubungi');

Route::get('/kerjasama/daftar', 'Frontend\KerjasamaController@daftar')->name('kerjasama.daftar');

Route::get('/kerjasama/rekapitulasi', 'Frontend\KerjasamaController@rekap')->name('kerjasama.rekap');

Route::get('/kerjasama/mitra', 'Frontend\KerjasamaController@mitra')->name('kerjasama.mitra');

Route::get('/informasi/{slug}', 'Frontend\InformasiController@byslug')->name('informasi.berita');

Route::get('/ventura/{slug}', 'Frontend\VenturaController@byslug')->name('ventura.slug');

Route::get('/all/ventura', 'Frontend\VenturaController@daftar')->name('ventura.all');

Route::get('/galeri/kumpulan-foto', 'Frontend\GaleriController@foto')->name('galeri.foto');

Route::get('/galeri/kumpulan-video', 'Frontend\GaleriController@video')->name('galeri.video');

Route::get('/regulasi/download', 'Frontend\RegulasiController@index')->name('front.regulasi');

Route::get('/artikel/{slug}', 'Frontend\ArtikelController@byslug')->name('artikel.slug');

Route::get('/kerjasama/usulan', 'Frontend\UsulanKerjasamaController@create')->name('kerjasama.ajukan');

Route::post('/kerjasama/usulan', 'Backend\UsulanKerjasamaController@store')->name('usulan.store');

Route::get('/kerjasama/tracking', 'Frontend\TrackingController@form')->name('kerjasama.tracking');

Route::post('/kerjasama/tracking/search', 'Frontend\TrackingController@search')->name('kerjasama.search');

Route::get('/asdf/{filename}', 'Frontend\TrackingController@download')->name('usulan.download');

Auth::routes();

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\KategoriBerita;
use App\Models\JenisInstansi;
use App\Models\LaporanVentura;
use App\Models\Kerjasama;
use App\Models\Instansi;
use App\Models\Regulasi;
use App\Models\Ventura;
use App\Models\Berita;
use App\Models\Client;
use App\Models\Galeri;
use App\User;
use Auth;

class DashboardController extends Controller
{
    public function index()
    {
        if (Auth::user()->level==1) {
            $berita = Berita::orderby('id', 'desc')->limit(5)->get();
            $kategori = KategoriBerita::all();
            $pengguna = User::count();
            $regulasi = Regulasi::count();
            $galeri = Galeri::count();

            $label = null;
            $arrlabel = [];
            $id_arr = [];
            foreach ($kategori as $value) {
                $label .= "'".$value->kategori."',";
                $id_arr[] = $value->id;
                $arrlabel[] = $value->kategori;
            }

            $value = null;
            $index = 0;
            foreach ($id_arr as $key) {
                $counter = 0;
                foreach ($berita as $ber) {
                    if ($key==$ber->id_kategori) {
                        $counter++;
                    }
                }
                $value .= "{value:".$counter.", name:'".$arrlabel[$index]."'},";
                $index++;
            }

            return view('backend.pages.dashboard.web')
                ->with('kategori', $kategori->count())
                ->with('label', $label)
                ->with('value', $value)
                ->with('galeri', $galeri)
                ->with('regulasi', $regulasi)
                ->with('pengguna', $pengguna)
                ->with('berita', $berita);
        }

        if (Auth::user()->level==2) {
            $kerjasama = Kerjasama::with('instansi')
            ->with('sifat_kerjasama')
            ->limit(8)
            ->get();

            $kerjasamacount = Kerjasama::count();

            $mitra = Instansi::count();
        
            $ks_berlangsung = 0;
            foreach ($kerjasama as $ks) {
                if (($ks->tanggal_mulai <= date('Y-m-d')) && ($ks->tanggal_selesai >= date('Y-m-d'))) {
                    $ks_berlangsung++;
                }
            }

            $jenis_instansi = JenisInstansi::all();
            $kerjasama = Kerjasama::with('instansi')->get();

            $ji_label = null;
            $ji_value = null;
            if (!is_null($jenis_instansi)) {
                foreach ($jenis_instansi as $ji) {
                    $ji_label .= "'".$ji->nama."',";
                    $count_ks = 0;
                    foreach ($kerjasama as $ks) {
                        if ($ji->id==$ks->instansi->id_jenis_instansi) {
                            $count_ks++;
                        }
                    }
                    $ji_value .= "{value:".$count_ks.", name:'".$ji->nama."'},";
                }
            }

            return view('backend.pages.dashboard.kerjasama')
                ->with('ji_label', $ji_label)
                ->with('ji_value', $ji_value)
                ->with('mitra', $mitra)
                ->with('kerjasamacount', $kerjasamacount)
                ->with('ks_berlangsung', $ks_berlangsung)
                ->with('kerjasama', $kerjasama);
        }

        if (Auth::user()->level==3) {
            $ventura = Ventura::all();
            $laporan = LaporanVentura::all();

            $laporanshow = LaporanVentura::with('ventura')->limit(5)->get();

            $berlangsung = 0;
            $belummulai = 0;
            $sudahselesai = 0;
            
            foreach ($laporan as $item) {
                if (($item->tanggal_mulai <= date('Y-m-d')) && ($item->tanggal_selesai >= date('Y-m-d'))) {
                    $berlangsung++;
                } else if(($item->tanggal_mulai >= date('Y-m-d'))) {
                    $belummulai++;
                } else if(($item->tanggal_selesai < date('Y-m-d'))) {
                    $sudahselesai++;
                }
            }

            return view('backend.pages.dashboard.ventura')
                ->with('berlangsung', $berlangsung)
                ->with('belummulai', $belummulai)
                ->with('sudahselesai', $sudahselesai)
                ->with('laporancount', $laporan->count())
                ->with('laporanshow', $laporanshow)
                ->with('venturacount', $ventura->count());       
        }

        if (Auth::user()->level==4) {
            $ventura = Ventura::all();
            $laporan = LaporanVentura::all();
            $kerjasamacount = Kerjasama::count();
            $kerjasama = Kerjasama::all();

            $laporanshow = LaporanVentura::with('ventura')->limit(5)->get();

            $v_berlangsung = 0;
            $v_belummulai = 0;
            $v_sudahselesai = 0;
            foreach ($laporan as $item) {
                if (($item->tanggal_mulai <= date('Y-m-d')) && ($item->tanggal_selesai >= date('Y-m-d'))) {
                    $v_berlangsung++;
                } else if(($item->tanggal_mulai >= date('Y-m-d'))) {
                    $v_belummulai++;
                } else if(($item->tanggal_selesai < date('Y-m-d'))) {
                    $v_sudahselesai++;
                }
            }

            $k_berlangsung = 0;
            $k_belummulai = 0;
            $k_sudahselesai = 0;
            foreach ($kerjasama as $item) {
                if (($item->tanggal_mulai <= date('Y-m-d')) && ($item->tanggal_selesai >= date('Y-m-d'))) {
                    $k_berlangsung++;
                } else if(($item->tanggal_mulai >= date('Y-m-d'))) {
                    $k_belummulai++;
                } else if(($item->tanggal_selesai < date('Y-m-d'))) {
                    $k_sudahselesai++;
                }
            }

            return view('backend.pages.dashboard.manajer')
                ->with('v_berlangsung', $v_berlangsung)
                ->with('v_belummulai', $v_belummulai)
                ->with('v_sudahselesai', $v_sudahselesai)
                ->with('k_berlangsung', $k_berlangsung)
                ->with('k_belummulai', $k_belummulai)
                ->with('k_sudahselesai', $k_sudahselesai)
                ->with('laporancount', $laporan->count())
                ->with('laporanshow', $laporanshow)
                ->with('kerjasamacount', $kerjasamacount)
                ->with('venturacount', $ventura->count());     
        }

        if (Auth::user()->level==5) {
            $laporan = LaporanVentura::where('id_ventura', Auth::user()->ventura->id)->get();

            $laporanshow = LaporanVentura::where('id_ventura', Auth::user()->ventura->id)
                ->with('ventura')->limit(5)->get();

            $client = Client::where('id_ventura', Auth::user()->ventura->id)->count();

            $berlangsung = 0;
            $belummulai = 0;
            $sudahselesai = 0;
            foreach ($laporan as $item) {
                if (($item->tanggal_mulai <= date('Y-m-d')) && ($item->tanggal_selesai >= date('Y-m-d'))) {
                    $berlangsung++;
                } else if(($item->tanggal_mulai >= date('Y-m-d'))) {
                    $belummulai++;
                } else if(($item->tanggal_selesai < date('Y-m-d'))) {
                    $sudahselesai++;
                }
            }

            return view('backend.pages.dashboard.kepala')
                ->with('client', $client)
                ->with('berlangsung', $berlangsung)
                ->with('belummulai', $belummulai)
                ->with('sudahselesai', $sudahselesai)
                ->with('laporancount', $laporan->count())
                ->with('laporanshow', $laporanshow);
        }
    }
}

resources/views/backend/pages/dashboard/web.blade.php
@extends('backend.layouts.master')

@section('content')

	<div class="row">
		<div class="col-md-6 col-sm-6">
			<div class="widget p-md clearfix">
				<div class="pull-left">
					<h3 class="widget-title">Hello, {{ Auth::user()->name }}.</h3>
					<small class="text-color">
						Login Sebagai 
						@if (Auth::user()->level==1)
							Web Administrator
						@endif
						@if (Auth::user()->level==2)
							Administrator Kerjasama
						@endif
						@if (Auth::user()->level==3)
							Administrator Ventura
						@endif
						@if (Auth::user()->level==4)
							Manajer Kerjasama & Ventura
						@endif
						@if (Auth::user()->level==5)
							Kepala Ventura
						@endif
						@if (Auth::user()->level==6)
							Pengusul Kerjasama
						@endif
						@if (Auth::user()->level==7)
							Administrator Aset
						@endif
					</small>
				</div>
				<span class="pull-right fz-lg fw-500 counter">
					<i class="fa fa-user text-success" style="font-size:30px;"></i>
				</span>
			</div><!-- .widget -->
		</div>

		<div class="col-md-6 col-sm-6">
			<div class="widget p-md clearfix">
				<div class="pull-left">
					<h3 class="widget-title">Jumlah Pengguna</h3>
					<small class="text-color">Aktif</small>
				</div>
				<span class="pull-right fz-lg fw-500 counter" data-plugin="counterUp">{{ $pengguna }}</span>
			</div><!-- .widget -->
		</div>
	</div>

	<div class="row">
		<div class="col-md-3 col-sm-6">
			<div class="widget stats-widget">
				<div class="widget-body clearfix">
					<div class="pull-left">
						<h3 class="widget-title text-primary"><span class="counter" data-plugin="counterUp">{{ $berita->count() }}</span></h3>
						<small class="text-color">Jumlah Berita</small>
					</div>
					<span class="pull-right big-icon watermark"><i class="fa fa-list"></i></span>
				</div>
				<a href="{{ route('berita.index') }}">
					<footer class="widget-footer bg-primary">
						<small>Lihat Detail</small>
						<span class="small-chart pull-right" data-plugin="sparkline" data-options="[4,3,5,2,1], { type: 'bar', barColor: '#ffffff', barWidth: 5, barSpacing: 2 }"><canvas width="33" height="16" style="display: inline-block; width: 33px; height: 16px; vertical-align: top;"></canvas></span>
					</footer>
				</a>
			</div><!-- .widget -->
		</div>

		<div class="col-md-3 col-sm-6">
			<div class="widget stats-widget">
				<div class="widget-body clearfix">
					<div class="pull-left">
						<h3 class="widget-title text-danger"><span class="counter" data-plugin="counterUp">{{ $regulasi }}</span></h3>
						<small class="text-color">Jumlah Regulasi</small>
					</div>
					<span class="pull-right big-icon watermark"><i class="fa fa-ban"></i></span>
				</div>
				<a href="{{ route('regulasi.index') }}">
					<footer class="widget-footer bg-danger">
						<small>Lihat Detail</small>
						<span class="small-chart pull-right" data-plugin="sparkline" data-options="[4,3,5,2,1], { type: 'bar', barColor: '#ffffff', barWidth: 5, barSpacing: 2 }"><canvas width="33" height="16" style="display: inline-block; width: 33px; height: 16px; vertical-align: top;"></canvas></span>
					</footer>
				</a>
			</div><!-- .widget -->
		</div>

		<div class="col-md-3 col-sm-6">
			<div class="widget stats-widget">
				<div class="widget-body clearfix">
					<div class="pull-left">
						<h3 class="widget-title text-success"><span class="counter" data-plugin="counterUp">{{ $galeri }}</span></h3>
						<small class="text-color">Jumlah Galeri</small>
					</div>
					<span class="pull-right big-icon watermark"><i class="fa fa-image"></i></span>
				</div>
				<a href="{{ route('galeri-foto.index') }}">
					<footer class="widget-footer bg-warning">
						<small>Lihat Detail</small>
						<span class="small-chart pull-right" data-plugin="sparkline" data-options="[4,3,5,2,1], { type: 'bar', barColor: '#ffffff', barWidth: 5, barSpacing: 2 }"><canvas width="33" height="16" style="display: inline-block; width: 33px; height: 16px; vertical-align: top;"></canvas></span>
					</footer>
				</a>
			</div><!-- .widget -->
        </div>
        
        <div class="col-md-3 col-sm-6">
			<div class="widget stats-widget">
				<div class="widget-body clearfix">
					<div class="pull-left">
						<h3 class="widget-title text-success"><span class="counter" data-plugin="counterUp">{{ $kategori }}</span></h3>
						<small class="text-color">Jumlah Kategori</small>
					</div>
					<span class="pull-right big-icon watermark"><i class="fa fa-briefcase"></i></span>
				</div>
				<a href="{{ route('kategori-berita.index') }}">
					<footer class="widget-footer bg-success">
						<small>Lihat Detail</small>
						<span class="small-chart pull-right" data-plugin="sparkline" data-options="[4,3,5,2,1], { type: 'bar', barColor: '#ffffff', barWidth: 5, barSpacing: 2 }"><canvas width="33" height="16" style="display: inline-block; width: 33px; height: 16px; vertical-align: top;"></canvas></span>
					</footer>
				</a>
			</div><!-- .widget -->
		</div>
	</div>

	<div class="row">
        <div class="col-md-6">
			<div class="widget">
			<header class="widget-header">
				<h4 class="widget-title">Persentase Berita Berdasarkan Kategori</h4>
			</header><!-- .widget-header -->
			<hr class="widget-separator">
			<div class="widget-body">
				<div data-plugin="chart" data-options="{
					tooltip : {
						trigger: 'item',
						formatter: '{a} <br/>{b} : {c} ({d}%)'
					},
					legend: {
						orient: 'vertical',
						x: 'left',
						data: [ {{ $label }} ]
					},
					series : [
						{
							name: 'Persentase Data',
							type: 'pie',
							radius : '55%',
							center: ['50%', '60%'],
							data:[ {{ $value }} ],
							itemStyle: {
								emphasis: {
									shadowBlur: 10,
									shadowOffsetX: 0,
									shadowColor: 'rgba(0, 0, 0, 0.5)'
								}
							}
						}
					]
				}" style="height: 300px; -webkit-tap-highlight-color: transparent; user-select: none; background-color: rgba(0, 0, 0, 0); cursor: default;" _echarts_instance_="1531196547417"><div style="position: relative; overflow: hidden; width: 462px; height: 300px;"><div data-zr-dom-id="bg" class="zr-element" style="position: absolute; left: 0px; top: 0px; width: 462px; height: 300px; user-select: none;"></div><canvas width="462" height="300" data-zr-dom-id="0" class="zr-element" style="position: absolute; left: 0px; top: 0px; width: 462px; height: 300px; user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></canvas><canvas width="462" height="300" data-zr-dom-id="1" class="zr-element" style="position: absolute; left: 0px; top: 0px; width: 462px; height: 300px; user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></canvas><canvas width="462" height="300" data-zr-dom-id="_zrender_hover_" class="zr-element" style="position: absolute; left: 0px; top: 0px; width: 462px; height: 300px; user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></canvas><div class="echarts-tooltip zr-element" style="position: absolute; display: none; border-style: solid; white-space: nowrap; transition: left 0.4s, top 0.4s; background-color: rgba(0, 0, 0, 0.9); border-width: 0px; border-color: rgb(51, 51, 51); border-radius: 4px; color: rgb(255, 255, 255); padding: 12px 16px; top: 140px; left: 234px;">Persentase Data <br>Asosiasi Industri : 1 (50.00%)</div></div></div>
			</div><!-- .widget-body -->
			</div><!-- .widget -->
		</div>
		<div class="col-md-6">
			<div class="widget">
				<header class="widget-header">
					<h4 class="widget-title">Berita Terakhir</h4>
				</header>
				<hr class="widget-separator">
				<div class="widget-body">
					<div class="table-responsive">							
						<table class="table table-striped">
							<thead>
								<tr>
									<th style="width:40px;">#</th>
									<th>Judul</th>
									<th>Tanggal</th>
									<th>Status</th>
								</tr>
							</thead>
							<tbody>
								@foreach ($berita as $key => $item)
                                    <tr>
                                        <td>{{ $key = $key + 1 }}</td>
                                        <td>{{ $item->judul }}</td>
                                        <td>{{ \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $item->created_at)->toFormattedDateString() }}</td>
                                        <td>
                                            @if ($item->flag==1)
                                                <span class="label label-success">Aktif</span>
                                            @else
                                                <span class="label label-danger">Non Aktif</span>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
							</tbody>
                        </table>
                        <br>
                        <div class="text-center">
                            <a href="{{ route('berita.index') }}" class="btn btn-default btn-xs">Lihat Selengkapnya</a>
                        </div>
					</div>
				</div>
			</div><!-- .widget -->
		</div>
	</div>
@endsection