routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\FrontController@index')->name('frontend.index');

Route::get('/dashboard', 'Backend\DashboardController@index')->name('backend.dashboard')->middleware('auth');

Route::resource('/backend/sejarah', 'Backend\SejarahController')->middleware('isWebAdmin');

Route::resource('/backend/tugas-fungsi', 'Backend\TugasFungsiController')->middleware('isWebAdmin');

Route::resource('/backend/struktur-organisasi', 'Backend\StrukturOrganisasiController')->middleware('isWebAdmin');

Route::resource('/backend/visi-misi', 'Backend\VisiMisiController')->middleware('isWebAdmin');

Route::resource('/backend/hubungi-kami', 'Backend\HubungiKamiController')->middleware('isWebAdmin');

Route::resource('/backend/ventura', 'Backend\VenturaController');

Route::resource('/backend/laporan-ventura', 'Backend\LaporanVenturaController')->middleware('isKepalaVentura');

Route::get('/backend/all/laporan-ventura', 'Backend\LaporanVenturaController@getall')->name('laporan-ventura.all');

Route::get('/backend/laporan-ventura/detail/{id}', 'Backend\LaporanVenturaController@detail')->name('laporan-ventura.detail');

Route::resource('/backend/kategori-berita', 'Backend\KategoriBeritaController')->middleware('isWebAdmin');

Route::resource('/backend/berita', 'Backend\BeritaController')->middleware('isWebAdmin');

Route::resource('/backend/galeri-foto', 'Backend\GaleriFotoController')->middleware('isWebAdmin');

Route::resource('/backend/galeri-video', 'Backend\GaleriVideoController')->middleware('isWebAdmin');

Route::resource('/backend/slider', 'Backend\SliderController')->middleware('isWebAdmin');

Route::resource('/backend/jenis-instansi', 'Backend\JenisInstansiController')->middleware('isAdminKerjasama');

Route::resource('/backend/sifat-kerjasama', 'Backend\SifatKerjasamaController')->middleware('isAdminKerjasama');

Route::resource('/backend/instansi', 'Backend\InstansiController')->middleware('isAdminKerjasama');

Route::resource('/backend/kerjasama', 'Backend\KerjasamaController');

Route::get('detail-kerjasama/{id}', 'Backend\KerjasamaController@detail');

Route::get('/backend/kerjasama/download-dokumen/{filename}', 'Backend\KerjasamaController@download')->name('kerjasama.download');

Route::get('hapus-dokumen-kerjasama/{id}', 'Backend\DokumenKerjasamaController@delete')->name('dokumen-kerjasama.destroy');

Route::get('hapus-dokumen-ventura/{id}', 'Backend\DokumenVenturaController@delete')->name('dokumen-ventura.destroy');

Route::resource('/backend/regulasi', 'Backend\RegulasiController')->middleware('isWebAdmin');

Route::resource('/backend/pengguna', 'Backend\PenggunaController')->middleware('isWebAdmin');

Route::get('/backend/rekapitulasi-kerjasama', 'Backend\RekapitulasiKerjasamaController@chart')->name('rekap-kerjasama.index');

Route::resource('/backend/client', 'Backend\ClientController')->middleware('isKepalaVentura');

Route::get('/backend/admin/client', 'Backend\ClientController@getall')->name('client.all');

Route::resource('/backend/laporan-keuangan', 'Backend\LaporanKeuanganController');

Route::resource('/backend/status-usulan', 'Backend\StatusUsulanController')->middleware('isAdminKerjasama');

Route::post('kontribusi-ui/store/{id}', 'Backend\LaporanKeuanganController@kontribusi')->name('kontribusi-ui.store');

Route::get('/profile/sejarah', 'Frontend\ProfileController@sejarah')->name('front.sejarah');

Route::get('/profile/tugas-fungsi', 'Frontend\ProfileController@tugasfungsi')->name('front.tugas');

Route::get('/profile/struktur-organisasi', 'Frontend\ProfileController@strukturorg')->name('front.struktur');

Route::get('/profile/visi-misi', 'Frontend\ProfileController@visimisi')->name('front.visi');

Route::get('/profile/hubungi-kami', 'Frontend\ProfileController@hubungi')->name('front.hubungi');

Route::get('/kerjasama/daftar', 'Frontend\KerjasamaController@daftar')->name('kerjasama.daftar');

Route::get('/kerjasama/rekapitulasi', 'Frontend\KerjasamaController@rekap')->name('kerjasama.rekap');

Route::get('/kerjasama/mitra', 'Frontend\KerjasamaController@mitra')->name('kerjasama.mitra');

Route::get('/informasi/{slug}', 'Frontend\InformasiController@byslug')->name('informasi.berita');

Route::get('/ventura/{slug}', 'Frontend\VenturaController@byslug')->name('ventura.slug');

Route::get('/all/ventura', 'Frontend\VenturaController@daftar')->name('ventura.all');

Route::get('/galeri/kumpulan-foto', 'Frontend\GaleriController@foto')->name('galeri.foto');

Route::get('/galeri/kumpulan-video', 'Frontend\GaleriController@video')->name('galeri.video');

Route::get('/regulasi/download', 'Frontend\RegulasiController@index')->name('front.regulasi');

Route::get('/artikel/{slug}', 'Frontend\ArtikelController@byslug')->name('artikel.slug');

Route::get('/kerjasama/usulan', 'Frontend\UsulanKerjasamaController@create')->name('kerjasama.ajukan');

Route::post('/kerjasama/usulan', 'Backend\UsulanKerjasamaController@store')->name('usulan.store');

Route::get('/kerjasama/tracking', 'Frontend\TrackingController@form')->name('kerjasama.tracking');

Route::post('/kerjasama/tracking/search', 'Frontend\TrackingController@search')->name('kerjasama.search');

Route::get('/asdf/{filename}', 'Frontend\TrackingController@download')->name('usulan.download');

Auth::routes();

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Client extends Model
{
    use SoftDeletes;

    protected $table = "client";

    protected $fillable = [ 
        'id_ventura', 'id_jenis_instansi', 'nama', 'alamat', 'telp', 'flag'
    ];

    public function ventura()
    {
        return $this->belongsTo('App\Models\Ventura', 'id_ventura');
    }

    public function jenis_instansi()
    {
        return $this->belongsTo('App\Models\JenisInstansi', 'id_jenis_instansi');
    }
}

app/Http/Controllers/Backend/ClientController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Client;
use App\Models\Ventura;
use App\Models\JenisInstansi;
use Validator;
use Auth;
use DB;

class ClientController extends Controller
{
    public function index()
    {
        $client = Client::where('id_ventura', Auth::user()->ventura->id)
            ->with('ventura')
            ->with('jenis_instansi')
            ->get();
        
        $jenis_instansi = JenisInstansi::all();
        
        return view('backend.pages.client.index')
            ->with('jenis_instansi', $jenis_instansi)
            ->with('client', $client);
    }

    public function getall()
    {
        $client = Client::with('ventura')
            ->with('jenis_instansi')
            ->get();
        
        $jenis_instansi = JenisInstansi::all();
        
        return view('backend.pages.client.index')
            ->with('jenis_instansi', $jenis_instansi)
            ->with('client', $client);
    }

    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'id_jenis_instansi' => 'required',
            'nama' => 'required',
            'alamat' => 'required',
            'telp' => 'required|numeric',
        ])->validate();

        $insert = new Client;
        $insert->id_ventura = Auth::user()->ventura->id;
        $insert->id_jenis_instansi = $request->id_jenis_instansi;
        $insert->nama = $request->nama;
        $insert->alamat = $request->alamat;
        $insert->telp = $request->telp;
        $insert->save();

        return redirect()->route('client.index')
            ->with('success', 'Anda telah memasukkan data baru.');
    }

    public function edit($id)
    {
        return Client::find($id);
    }

    public function update(Request $request, $id)
    {
        Validator::make($request->all(), [
            'id_jenis_instansi' => 'required',
            'nama' => 'required',
            'alamat' => 'required',
            'telp' => 'required|numeric',
        ])->validate();

        $insert = Client::find($id);
        $insert->id_ventura = Auth::user()->ventura->id;
        $insert->id_jenis_instansi = $request->id_jenis_instansi;
        $insert->nama = $request->nama;
        $insert->alamat = $request->alamat;
        $insert->telp = $request->telp;
        $insert->save();

        return redirect()->route('client.index')
            ->with('success', 'Anda telah mengubah data baru.');
    }

    public function destroy($id)
    {
        Client::destroy($id);

        return redirect()->route('client.index')
            ->with('success', 'Anda telah menghapus data client.');
    }
}

resources/views/backend/pages/client/index.blade.php
@extends('backend.layouts.master')

@section('alert-error')
	@if (Session::has('errors'))
		<div class="col-md-12">
			<div class="alert alert-danger alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
				<strong>Oops, terjadi kesalahan. </strong>
				<ul style="font-size:12px;margin-top:5px;">
					@if ($errors->has('id_ventura'))
						<li> &nbsp; - {{ $errors->first('id_ventura') }}</li>
					@endif
					@if ($errors->has('id_jenis_instansi'))
						<li> &nbsp; - {{ $errors->first('id_jenis_instansi') }}</li>
					@endif
					@if ($errors->has('nama'))
						<li> &nbsp; - {{ $errors->first('nama') }}</li>
					@endif
					@if ($errors->has('alamat'))
						<li> &nbsp; - {{ $errors->first('alamat') }}</li>
					@endif
					@if ($errors->has('telp'))
						<li> &nbsp; - {{ $errors->first('telp') }}</li>
					@endif
				</ul>
			</div>
		</div>
    @endif
@endsection

@section('modal')
	<div class="modal fade" id="modaltambah" tabindex="-1" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Tambah Data Client</h4>
				</div>
				<div class="modal-body">
					<form action="{{ route('client.store') }}" method="POST">
						@csrf
						<div class="form-group">
							<select name="id_jenis_instansi" class="form-control">
                                <option value="">-- Pilih Jenis Instansi --</option>
                                @foreach ($jenis_instansi as $ji)
                                    <option value="{{ $ji->id }}">{{ $ji->nama }}</option>
                                @endforeach
                            </select>
						</div>
						<div class="form-group">
							<input name="nama" type="text" class="form-control" placeholder="Nama Client">
						</div>
						<div class="form-group">
							<textarea name="alamat" cols="30" rows="10" class="form-control" placeholder="Alamat Client"></textarea>
						</div>
						<div class="form-group">
							<input name="telp" type="text" class="form-control" placeholder="Telepon Client">
						</div>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn btn-default">Batal</button>
					<input type="submit" class="btn btn-success" value="Simpan">
				</div>
				</form>
			</div>
		</div>
	</div>

	<div class="modal fade" id="modalubah" tabindex="-1" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Ubah Data Client</h4>
				</div>
				<div class="modal-body">
					<form id="form-update" method="POST">
						@csrf
						@method('PUT')
						<div class="form-group">
							<select name="id_jenis_instansi" class="form-control" id="id_jenis_instansi">
                                <option value="">-- Pilih Jenis client --</option>
                                @foreach ($jenis_instansi as $ji)
                                    <option value="{{ $ji->id }}">{{ $ji->nama }}</option>
                                @endforeach
                            </select>
						</div>
						<div class="form-group">
							<input name="nama" type="text" class="form-control" placeholder="Nama Client" id="nama">
						</div>
						<div class="form-group">
							<textarea name="alamat" cols="30" rows="10" class="form-control" id="alamat"></textarea>
						</div>
						<div class="form-group">
							<input name="telp" type="text" class="form-control" placeholder="Telepon Client" id="telp">
						</div>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn btn-default">Batal</button>
					<input type="submit" class="btn btn-success" value="Simpan Perubahan">
				</div>
				</form>
			</div>
		</div>
	</div>

	<div class="modal fade" id="modalhapus" tabindex="-1" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Konfirmasi Hapus Data Client</h4>
				</div>
				<div class="modal-body">
					<h5>Apakah anda yakin akan menghapus data ini?</h5>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn btn-default">Batal</button>
					<a class="btn btn-danger" onclick="event.preventDefault(); document.getElementById('form-delete').submit();" style="cursor:pointer;">Ya, Saya Yakin</a>
					<form id="form-delete" method="POST" style="display: none;">
						@csrf
						@method('DELETE')
					</form>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('content')
	<div class="col-md-12">
		<div class="widget">
			<header class="widget-header">
				<span class="widget-title">Data Client</span>
				@if (Auth::user()->level==5)
					<a href="" class="btn btn-sm btn-success pull-right" data-toggle="modal" data-target="#modaltambah">+ Tambah Data</a>
				@endif
			</header><!-- .widget-header -->
			<hr class="widget-separator">
			<div class="widget-body">
				<div class="table-responsive">
					<table id="table" data-plugin="DataTable" class="table table-striped" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th style="width:15px;">#</th>
								@if (Auth::user()->level==3)
									<th>Ventura</th>
								@endif
								<th>Nama Client</th>
								<th>Alamat</th>
								<th>Telepon</th>
								<th>Jenis Instansi</th>
								@if (Auth::user()->level==5)
									<th>Aksi</th>
								@endif
							</tr>
						</thead>
						<tbody>
                            @foreach ($client as $index => $item)
                                <tr>
									<td>{{ $index = $index + 1 }}</td>
									@if (Auth::user()->level==3)
										<td>{{ $item->ventura->nama }}</td>
									@endif
                                    <td>{{ $item->nama }}</td>
                                    <td>{{ $item->alamat }}</td>
                                    <td>{{ $item->telp }}</td>
									<td>{{ $item->jenis_instansi->nama }}</td>
									@if (Auth::user()->level==5)
										<td>
											<a href="" class="btn btn-xs btn-warning btn-edit" data-value="{{ $item->id }}" data-toggle="modal" data-target="#modalubah"><i class="fa fa-edit"></i></a>
											<a href="" class="btn btn-xs btn-danger btn-delete" data-value="{{ $item->id }}" data-toggle="modal" data-target="#modalhapus"><i class="fa fa-trash"></i></a>
										</td>
									@endif
                                </tr>
                            @endforeach
						</tbody>
					</table>
				</div>
			</div><!-- .widget-body -->
		</div><!-- .widget -->
	</div>
@endsection

@section('footscript')
	<script>
		// binding data to modal edit
        $('#table').on('click', '.btn-edit', function(){
            var id = $(this).data('value')
			
            $.ajax({
                url: "{{ url('backend/client') }}/"+id+"/edit",
                success: function(res) {
					$('#form-update').attr('action', "{{ url('backend/client') }}/"+id)

					$('#id_jenis_instansi').val(res.id_jenis_instansi)
					$('#nama').val(res.nama)
					$('#alamat').val(res.alamat)
					$('#telp').val(res.telp)
                }
            })
        })

		// delete action
        $('#table').on('click', '.btn-delete', function(){
            var id = $(this).data('value')
			$('#form-delete').attr('action', "{{ url('backend/client') }}/"+id)			
        })
	</script>
@endsection