routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\FrontController@index')->name('frontend.index');

Route::get('/dashboard', 'Backend\DashboardController@index')->name('backend.dashboard')->middleware('auth');

Route::resource('/backend/sejarah', 'Backend\SejarahController')->middleware('isWebAdmin');

Route::resource('/backend/tugas-fungsi', 'Backend\TugasFungsiController')->middleware('isWebAdmin');

Route::resource('/backend/struktur-organisasi', 'Backend\StrukturOrganisasiController')->middleware('isWebAdmin');

Route::resource('/backend/visi-misi', 'Backend\VisiMisiController')->middleware('isWebAdmin');

Route::resource('/backend/hubungi-kami', 'Backend\HubungiKamiController')->middleware('isWebAdmin');

Route::resource('/backend/ventura', 'Backend\VenturaController');

Route::resource('/backend/laporan-ventura', 'Backend\LaporanVenturaController')->middleware('isKepalaVentura');

Route::get('/backend/all/laporan-ventura', 'Backend\LaporanVenturaController@getall')->name('laporan-ventura.all');

Route::get('/backend/laporan-ventura/detail/{id}', 'Backend\LaporanVenturaController@detail')->name('laporan-ventura.detail');

Route::resource('/backend/kategori-berita', 'Backend\KategoriBeritaController')->middleware('isWebAdmin');

Route::resource('/backend/berita', 'Backend\BeritaController')->middleware('isWebAdmin');

Route::resource('/backend/galeri-foto', 'Backend\GaleriFotoController')->middleware('isWebAdmin');

Route::resource('/backend/galeri-video', 'Backend\GaleriVideoController')->middleware('isWebAdmin');

Route::resource('/backend/slider', 'Backend\SliderController')->middleware('isWebAdmin');

Route::resource('/backend/jenis-instansi', 'Backend\JenisInstansiController')->middleware('isAdminKerjasama');

Route::resource('/backend/sifat-kerjasama', 'Backend\SifatKerjasamaController')->middleware('isAdminKerjasama');

Route::resource('/backend/instansi', 'Backend\InstansiController')->middleware('isAdminKerjasama');

Route::resource('/backend/kerjasama', 'Backend\KerjasamaController');

Route::get('detail-kerjasama/{id}', 'Backend\KerjasamaController@detail');

Route::get('/backend/kerjasama/download-dokumen/{filename}', 'Backend\KerjasamaController@download')->name('kerjasama.download');

Route::get('hapus-dokumen-kerjasama/{id}', 'Backend\DokumenKerjasamaController@delete')->name('dokumen-kerjasama.destroy');

Route::get('hapus-dokumen-ventura/{id}', 'Backend\DokumenVenturaController@delete')->name('dokumen-ventura.destroy');

Route::resource('/backend/regulasi', 'Backend\RegulasiController')->middleware('isWebAdmin');

Route::resource('/backend/pengguna', 'Backend\PenggunaController')->middleware('isWebAdmin');

Route::get('/backend/rekapitulasi-kerjasama', 'Backend\RekapitulasiKerjasamaController@chart')->name('rekap-kerjasama.index');

Route::resource('/backend/client', 'Backend\ClientController')->middleware('isKepalaVentura');

Route::get('/backend/admin/client', 'Backend\ClientController@getall')->name('client.all');

Route::resource('/backend/laporan-keuangan', 'Backend\LaporanKeuanganController');

Route::resource('/backend/status-usulan', 'Backend\StatusUsulanController')->middleware('isAdminKerjasama');

Route::post('kontribusi-ui/store/{id}', 'Backend\LaporanKeuanganController@kontribusi')->name('kontribusi-ui.store');

Route::get('/profile/sejarah', 'Frontend\ProfileController@sejarah')->name('front.sejarah');

Route::get('/profile/tugas-fungsi', 'Frontend\ProfileController@tugasfungsi')->name('front.tugas');

Route::get('/profile/struktur-organisasi', 'Frontend\ProfileController@strukturorg')->name('front.struktur');

Route::get('/profile/visi-misi', 'Frontend\ProfileController@visimisi')->name('front.visi');

Route::get('/profile/hubungi-kami', 'Frontend\ProfileController@hubungi')->name('front.hubungi');

Route::get('/kerjasama/daftar', 'Frontend\KerjasamaController@daftar')->name('kerjasama.daftar');

Route::get('/kerjasama/rekapitulasi', 'Frontend\KerjasamaController@rekap')->name('kerjasama.rekap');

Route::get('/kerjasama/mitra', 'Frontend\KerjasamaController@mitra')->name('kerjasama.mitra');

Route::get('/informasi/{slug}', 'Frontend\InformasiController@byslug')->name('informasi.berita');

Route::get('/ventura/{slug}', 'Frontend\VenturaController@byslug')->name('ventura.slug');

Route::get('/all/ventura', 'Frontend\VenturaController@daftar')->name('ventura.all');

Route::get('/galeri/kumpulan-foto', 'Frontend\GaleriController@foto')->name('galeri.foto');

Route::get('/galeri/kumpulan-video', 'Frontend\GaleriController@video')->name('galeri.video');

Route::get('/regulasi/download', 'Frontend\RegulasiController@index')->name('front.regulasi');

Route::get('/artikel/{slug}', 'Frontend\ArtikelController@byslug')->name('artikel.slug');

Route::get('/kerjasama/usulan', 'Frontend\UsulanKerjasamaController@create')->name('kerjasama.ajukan');

Route::post('/kerjasama/usulan', 'Backend\UsulanKerjasamaController@store')->name('usulan.store');

Route::get('/kerjasama/tracking', 'Frontend\TrackingController@form')->name('kerjasama.tracking');

Route::post('/kerjasama/tracking/search', 'Frontend\TrackingController@search')->name('kerjasama.search');

Route::get('/asdf/{filename}', 'Frontend\TrackingController@download')->name('usulan.download');

Auth::routes();

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/Berita.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Berita extends Model
{
    use SoftDeletes;

    protected $table = "berita";

    protected $fillable = [ 
        'id_kategori', 'id_author', 'judul', 'slug', 'foto_utama', 'konten', 'flag'
    ];

    public function kategori()
    {
        return $this->belongsTo('App\Models\KategoriBerita', 'id_kategori');
    }

    public function user()
    {
        return $this->belongsTo('App\User', 'id_author');
    }
}

app/Http/Controllers/Backend/BeritaController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\KategoriBerita;
use App\Models\Berita;
use Validator;
use Image;
use Input;
use Auth;

class BeritaController extends Controller
{
    public function index()
    {
        $data = Berita::with('kategori')->get();

        return view('backend.pages.berita.index')
            ->with('data', $data);
    }
    
    public function create()
    {
        $kategori = KategoriBerita::all();

        return view('backend.pages.berita.create')
            ->with('kategori', $kategori);
    }

    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'id_kategori' => 'required',
            'judul' => 'required',
            'konten' => 'required',
        ])->validate();

        $insert = new Berita;
        $insert->id_kategori = $request->id_kategori;
        $insert->id_author = Auth::user()->id;
        $insert->judul = $request->judul;
        $insert->slug = str_slug($request->judul);
        $insert->konten = $request->konten;
        $insert->foto_utama = null;

        if ($request->hasFile('foto_utama')) {
            $file = $request->file('foto_utama');
            $path = public_path().'/images/';
            $filename = time()."_artikel_"."authorid".Auth::user()->id."_".strtolower($file->getClientOriginalName());
            $file->move($path, $filename);
            
            $insert->foto_utama = $filename;
        }
        
        $insert->save();

        return redirect()->route('berita.index')
            ->with('success', 'Anda telah memasukkan data baru.');
    }

    public function edit($id)
    {
        $data = Berita::find($id);
        $kategori = KategoriBerita::all();

        return view('backend.pages.berita.edit')
            ->with('kategori', $kategori)
            ->with('data', $data);
    }

    public function update(Request $request, $id)
    {
        Validator::make($request->all(), [
            'id_kategori' => 'required',
            'judul' => 'required',
            'konten' => 'required',
        ])->validate();

        $insert = Berita::find($id);
        $insert->id_kategori = $request->id_kategori;
        $insert->id_author = Auth::user()->id;
        $insert->judul = $request->judul;
        $insert->slug = str_slug($request->judul);
        $insert->konten = $request->konten;

        if ($request->hasFile('foto_utama')) {
            $file = $request->file('foto_utama');
            $path = public_path().'/images/';
            $filename = time()."_artikel_"."authorid".Auth::user()->id."_".strtolower($file->getClientOriginalName());
            $file->move($path, $filename);
            
            $insert->foto_utama = $filename;
        }
        
        $insert->save();

        return redirect()->route('berita.index')
            ->with('success', 'Anda telah memasukkan data baru.');
    }

    public function destroy($id)
    {
        Berita::destroy($id);

        return redirect()->route('berita.index')
            ->with('success', 'Anda telah menghapus data berita.');
    }
}

resources/views/backend/pages/berita/create.blade.php
@extends('backend.layouts.master')

@section('content')
	<div class="col-md-12">
        <div class="widget">
            <header class="widget-header">
                <h4 class="widget-title">Formulir Tambah Artikel</h4>
            </header><!-- .widget-header -->
            <hr class="widget-separator">
            <div class="widget-body">
                <form action="{{ route('berita.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label>Judul Artikel</label>
                        <input type="text" class="form-control" name="judul">
                    </div>
                    <div class="form-group">
                        <label>Kategori Artikel</label>
                        <select name="id_kategori" class="form-control">
                            <option value="">-- Pilih Kategori --</option>
                            @foreach ($kategori as $item)
                                <option value="{{ $item->id }}">{{ $item->kategori }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Foto Utama</label>
                        <input type="file" class="form-control" name="foto_utama">
                    </div>
                    <div class="form-group">
                        <label>Konten Artikel</label>
                        <textarea name="konten" id="ckeditor" cols="30" rows="10"></textarea>
                    </div>
                    <br>
                    <div class="user-card p-md">
                        <div class="media">
                            <div class="media-body">
                                <input type="submit" class="btn btn-success" value="Simpan">
                            </div>
                        </div>
                    </div>
                </form>
            </div><!-- .widget-body -->
        </div><!-- .widget -->
    </div>
@endsection

@section('footscript')
    <script src="{{ url('/') }}/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>

    <script>
        var APP_URL = "{{ url('/') }}"

        var options = {
            filebrowserImageBrowseUrl: APP_URL + '/laravel-filemanager?type=Images',
            filebrowserImageUploadUrl: APP_URL + '/laravel-filemanager/upload?type=Images&_token=',
            filebrowserBrowseUrl: APP_URL + '/laravel-filemanager?type=Files',
            filebrowserUploadUrl: APP_URL + '/laravel-filemanager/upload?type=Files&_token='
        };
    </script>

    <script>
        CKEDITOR.replace( 'ckeditor', options);
        CKEDITOR.config.extraPlugins = 'justify';
    </script>
@endsection

resources/views/backend/pages/berita/edit.blade.php
@extends('backend.layouts.master')

@section('title')
    <style>
        .stream-img {
            margin: 10px 0 15px;
        }
    </style>
@endsection

@section('content')
	<div class="col-md-12">
        <div class="widget">
            <header class="widget-header">
                <h4 class="widget-title">Formulir Ubah Artikel</h4>
            </header><!-- .widget-header -->
            <hr class="widget-separator">
            <div class="widget-body">
                <form action="{{ route('berita.update', $data->id) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label>Judul Artikel</label>
                        <input type="text" class="form-control" name="judul" value="{{ $data->judul }}">
                    </div>
                    <div class="form-group">
                        <label>Kategori Artikel</label>
                        <select name="id_kategori" class="form-control">
                            <option value="">-- Pilih Kategori --</option>
                            @foreach ($kategori as $item)
                                @if ($data->id_kategori==$item->id)
                                    <option value="{{ $item->id }}" selected>{{ $item->kategori }}</option>
                                @else
                                    <option value="{{ $item->id }}">{{ $item->kategori }}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Foto Utama</label><br>
                        <img class="stream-img" src="{{ asset('images') }}/{{ $data->foto_utama }}">
                        <input type="file" class="form-control" name="foto_utama">
                        <span class="help-block text-muted"><i>* Biarkan kosong jika tidak ingin diganti</i></span>
                    </div>
                    <div class="form-group">
                        <label>Konten Artikel</label>
                        <textarea name="konten" id="ckeditor" cols="30" rows="10">{{$data->konten}}</textarea>
                    </div>
                    <br>
                    <div class="user-card p-md">
                        <div class="media">
                            <div class="media-body">
                                <input type="submit" class="btn btn-success" value="Simpan">
                            </div>
                        </div>
                    </div>
                </form>
            </div><!-- .widget-body -->
        </div><!-- .widget -->
    </div>
@endsection

@section('footscript')
    <script src="{{ url('/') }}/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>

    <script>
        var APP_URL = "{{ url('/') }}"

        var options = {
            filebrowserImageBrowseUrl: APP_URL + '/laravel-filemanager?type=Images',
            filebrowserImageUploadUrl: APP_URL + '/laravel-filemanager/upload?type=Images&_token=',
            filebrowserBrowseUrl: APP_URL + '/laravel-filemanager?type=Files',
            filebrowserUploadUrl: APP_URL + '/laravel-filemanager/upload?type=Files&_token='
        };
    </script>

    <script>
        CKEDITOR.replace( 'ckeditor', options);
        CKEDITOR.config.extraPlugins = 'justify';
    </script>
@endsection

resources/views/backend/pages/berita/index.blade.php
@extends('backend.layouts.master')

@section('modal')
	<div class="modal fade" id="modalhapus" tabindex="-1" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Konfirmasi Hapus Data Berita</h4>
				</div>
				<div class="modal-body">
					<h5>Apakah anda yakin akan menghapus data ini?</h5>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn btn-default">Batal</button>
					<a class="btn btn-danger" onclick="event.preventDefault(); document.getElementById('form-delete').submit();" style="cursor:pointer;">Ya, Saya Yakin</a>
					<form id="form-delete" method="POST" style="display: none;">
						@csrf
						@method('DELETE')
					</form>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('content')
	<div class="col-md-12">
		<div class="widget">
			<header class="widget-header">
				<span class="widget-title">Data Seluruh Artikel</span>
				<a href="{{ route('berita.create') }}" class="btn btn-sm btn-success pull-right">+ Tambah Data</a>
			</header><!-- .widget-header -->
			<hr class="widget-separator">
			<div class="widget-body">
				<div class="table-responsive">
					<table id="table" data-plugin="DataTable" class="table table-striped" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th style="width:15px;">#</th>
								<th>Judul</th>
								<th>Kategori</th>
								<th>Tanggal Posting</th>
								<th>Jam Posting</th>
								<th>Status</th>
								<th>Aksi</th>
							</tr>
						</thead>
						<tbody>
							@foreach ($data as $key => $item)
								<tr>
									<td>{{ $key = $key + 1 }}</td>
									<td>{{ $item->judul }}</td>
									<td>{{ $item->kategori->kategori }}</td>
									<td>{{ date_format($item->updated_at, 'd-m-Y') }}</td>
									<td>{{ date_format($item->updated_at, 'H:i:s') }}</td>
									<td>
										@if ($item->flag==1)
											<span class="label bg-success">Aktif</span>
										@else
											<span class="label bg-danger">Non Aktif</span>
										@endif
										</td>
									<td>
										<a href="{{ route('berita.edit', $item->id) }}" class="btn btn-xs btn-warning btn-edit"><i class="fa fa-edit"></i></a>
										<a href="#" class="btn btn-xs btn-danger btn-delete" data-toggle="modal" data-target="#modalhapus" data-value="{{ $item->id }}"><i class="fa fa-trash"></i></a>
										<a href="#" class="btn btn-xs btn-primary"><i class="fa fa-arrow-right"></i></a>
									</td>
								</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div><!-- .widget-body -->
		</div><!-- .widget -->
	</div>
@endsection

@section('footscript')
	<script>
		// binding data to modal edit
        $('#table').on('click', '.btn-edit', function(){
            var id = $(this).data('value')
			
            $.ajax({
                url: "{{ url('backend/kategori-berita') }}/"+id+"/edit",
                success: function(res) {
					$('#form-update').attr('action', "{{ url('backend/kategori-berita') }}/"+id)

					$('#kategori').val(res.kategori)
                }
            })
        })

		// delete action
        $('#table').on('click', '.btn-delete', function(){
            var id = $(this).data('value')
			$('#form-delete').attr('action', "{{ url('backend/berita') }}/"+id)			
        })
	</script>
@endsection